AntMark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')), 
    path('users/', include('users.urls', namespace = 'users')),
    path('admin_manage/', include('admin_manage.urls', namespace = "admin_manage")),
    path('commodity/', include('commodity.urls', namespace = "commodity")),
    path('chatroom/',include('chatroom.urls', namespace = "chatroom")),
    path('ueditor/',include('DjangoUeditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\

admin_manage/urls.py
from django.urls import path

from admin_manage import views

app_name = 'admin_manage'

urlpatterns = [
    path('', views.admin_index, name = 'admin_index'),
    
    path('stu_verify_list', views.stu_verify_list, name = "stu_verify_list"),
    
    path('comm_verify_list', views.comm_verify_list, name = "comm_verify_list"),
    
    path('stu_verify_detail/<int:message_id>/<int:user_id>', views.stu_verify_detail, name = "stu_verify_detail"),

    path('comm_verify_detail/<int:message_id>/<int:comm_id>', views.comm_verify_detail, name = "comm_verify_detail"),

    path('create_anno/', views.create_anno, name = "create_anno"),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('del_message/<int:message_id>', views.del_message, name = 'del_message'),

    path('deal_mult_msg/', views.deal_mult_msg, name = 'deal_mult_msg'),
]

chatroom/urls.py
from django.urls import path

from chatroom import views

app_name = 'chatroom'

urlpatterns = [
    # 聊天室列表
    path('room_list/', views.room_list, name = 'room_list'),

    path('start_chat/<int:user_id>/<int:comm_id>', views.start_chat, name = 'start_chat'),

    path('room_detail/<int:room_id>', views.room_detail, name = 'room_detail'),

    path('get_messages/<int:room_id>', views.get_messages, name = 'get_messages'),

    path('del_room/<int:room_id>/<int:mem_id>', views.del_room, name = 'del_room'),

    path('chat_intro/', views.chat_intro, name = 'chat_intro'),
]

commodity/urls.py
from django.urls import path, re_path
from . import views

app_name = "commodity"
urlpatterns = [
    path('commodity-list/', views.commodity_list, name = "commodity_list"),
    path('commodity-detail/<int:commodity_id>/', views.commodity_detail, name = "commodity_detail"),
    path('search-commodity/', views.search_commodity, name = "search_commodity"),
    
    path('commodity-repertory/', views.commodity_repertory, name = "commodity_repertory"),
    path('edit-commodity/<int:commodity_id>/', views.edit_commodity, name = "edit_commodity"),
    path('preview-commodity/<int:commodity_id>/', views.preview_commodity, name = "preview_commodity"),
    path('create-commodity/', views.create_commodity, name = "create_commodity"),
    path('del-commodity/', views.del_commodity, name = "del_commodity"),
    path('put-on-shelves-list/', views.put_on_shelves_list, name = "put_on_shelves_list"),
    path('put-off-shelves-list/', views.put_off_shelves_list, name = "put_off_shelves_list"),
    path('put-off-commodity/', views.put_off_commodity, name = "put_off_commodity"),
    path('put-on-commodity/', views.put_on_commodity, name = "put_on_commodity"),
    path('not-verified-list/', views.not_verified_list, name = "not_verified_list"),
    path('commodity-verify/', views.commodity_verify, name="commodity_verify"),
    path('commodity-image/<int:commodity_id>/', views.commodity_image, name = "commodity_image"),
]

home/urls.py
from django.urls import path
import django.views

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name = 'index'),
    
    path('annos/', views.annos, name = 'annos'),

    path('about/', views.about, name = 'about'),
]

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    # 基础功能
    path('login/', views.login_view, name = 'login'),

    path('logout/', views.logout_view, name = 'logout'),

    path('register/', views.user_reg, name = 'register'),

    path('active/<str:active_code>', views.user_active, name = 'active'),

    path('settings/', views.user_settings, name = 'settings'),

    path('reset_pwd/', views.reset_password, name = 'reset_pwd'),

    path('personal_index/<int:user_id>', views.personal_index, name = 'personal_index'),

    path('stu_verify/', views.stu_verify, name = 'stu_verify'),

    
    # 消息处理相关
    path('mail_inbox/', views.mail_inbox, name = 'mail_inbox'),

    path('mail_outbox/', views.mail_outbox, name = 'mail_outbox'),

    path('call_admin/', views.call_admin, name = 'call_admin'),

    path('send_message/<int:user_id>', views.send_message, name = 'send_message'),

    path('set_as_read/<int:message_id>', views.set_as_read, name = 'set_as_read'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('del_message/<int:message_id>', views.del_message, name = 'del_message'),

    path('deal_mult_msg/', views.deal_mult_msg, name = 'deal_mult_msg'),

]

home/views.py
from django.shortcuts import render
from admin_manage.models import Announcement

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

def about(request):
    return render(request, 'home/about.html')

def annos(request):
    """ 查看公告 """
    annos = Announcement.objects.all()[:5]
    context = { 'annos': annos }
    return render(request, 'home/annos.html', context)

home/templates/home/about.html
<!DOCTYPE html> {% extends "home/base.html" %} {% block title %} About {% endblock %} {% block content %} {% load static %}

<body>
    <section class="section-gap info-area" id="about">
        <div class="container">
            <div class="col-md-5">
                <div class="text-center" style="margin-right:120px;">
                    <h1 class="mb-10">AntMark</h1>
                    <h4>双鸭山大学生的闲置物品交易平台</h4>
                    <br><br>
                </div>
                <div class="info-thumb">
                    <img src="{% static 'img/logo.png' %}" class="img-fluid" width="75%">
                </div>
                <a href="{% url 'users:call_admin' %}" class="btn btn-success btn-lg" style="margin:50px 0 0 24%;">联系管理员</a>
            </div>
            <div class="col-md-6" style="margin-right:20px;">
                <div class="info-content">
                    <h2 >网站介绍<br/></h2>
                    <hr>
                    <p>
                        在初次踏入中大自由的土壤时，面对琳琅满目的商品，你是否有过“挥金如土”之后无奈成为“吃土族”一员的辛酸？
                    </p>
                    <br>
                    <p>
                        每逢开学，当面对昂贵的教材，而手里却握着干瘪瘦弱的钱包时，你是否有过购买旧教材的冲动？
                    </p>
                    <br>
                    <p>
                        在毕业各奔前程之前，当你望着宿舍曾视如珍宝的大件物品，你是否会陷入“携之无力，弃之可惜”的苦恼？
                    </p>
                    <br>
                    <p>
                        那就加入AntMark吧，这是一个让中大莘莘学子轻松处理闲置物品的平台。我们承诺AntMark专注于为中大学生提供舒适便捷的交易体验。
                    </p>
                    <br>
                    <p>
                        AntMark的开发由一群热爱编程的小伙伴完成，目前他们也成了AntMark的管理员哦，欢迎来撩（轻轻点击“联系管理员”即可）~
                    </p>
                    <br>
                </div>
            </div>
        </div>
    </section>
    <!-- End about Area -->

    <hr/>
</body>
{% endblock content %}

home/templates/home/annos.html
<!DOCTYPE html> {% extends "home/base.html" %} {% block title %} Index {% endblock %} {% load static %} {% block content %}

<html lang="zxx" class="no-js">

<body>
<section class="project-area section-gap" id="project" style="padding-top: 50px">
    <div class="container">
        <div class="title text-center" style="margin-right:20px;">
            <h1 class="mb-10"><i class="fa fa-bullhorn"></i> 公告 </h1>
            <hr>
        </div>
        <div class="panel-group" id="accordion">
            {% for anno in annos %}
            <div class="panel panel-info" style="margin-right:20px;">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" href="#collapse{{forloop.counter}}">
                            <div class="row">
                                <div class="col-md-2 text-left">
                                    <p class="text-black">
                                        <i class="fa fa-bell-o"></i>
                                        {{ anno.title }}
                                    </p>  
                                </div>
                                <div class="col-md-3 col-md-offset-7 text-right">
                                    <p>
                                        <i class="fa fa-clock-o"></i>
                                        {{ anno.timestamp }}
                                    </p>
                                </div>
                            </div>
                        </a>
                    </h4>
                </div>
                <div id="collapse{{forloop.counter}}" class="panel-collapse collapse">
                    <div class="panel-body">
                        {{ anno.text | linebreaksbr }}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
</body>

</html>

{% endblock content %}

home/templates/home/base.html
<!DOCTYPE html> {% load bootstrap4 %} {% load staticfiles %} {% load base %}
<html lang="en">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static '/img/logo.png' %}">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>AntMark</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/typicons.min.css' %}">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/to-top.css' %}">
</head>

<body class="container" style="background-image: url({% static 'img/bg1.png' %});background-size:100% 150%;">
    <div class="container">
        <section class="banner-area" id="home">
            <nav id="navbar" class="navbar navbar-no-bg bg-primary navbar-fixed-top container navbar-dark"
                role="navigation" style="left:40px;">
                <div class="collapse navbar-collapse" id="top-navbar-1">
                    <a class="navbar-brand" href="{% url 'home:index' %}">
                        <img src="{% static '/img/AntMark.png' %}" alt="" height="40px"
                            style="margin: -10px 5px 0px -20px">
                    </a>
                    <ul class="nav navbar-nav navbar-left">
                        <li><a href="{% url 'home:index' %}"><i class="fa fa-home fa-lg"></i> 主页</a></li>
                        <li><a href="{% url 'commodity:commodity_list' %}"><i class="fa fa-shopping-cart fa-lg"></i> 商品</a></li>
                        <li><a href="{% url 'home:annos' %}"><i class="fa fa-bullhorn fa-lg"></i> 公告</a></li>
                        <li><a href="{% url 'home:about' %}"><i class="fa fa-info-circle fa-lg"></i> 了解我们</a></li>
                        {% if user.is_superuser %}
                        <li><a href="{% url 'admin_manage:admin_index' %}"><i class="fa fa-user-plus fa-lg"></i> 管理员中心</a></li>
                        {% endif %}
                    </ul>
                    {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'chatroom:room_list' %}"><i class="fa fa-comments-o fa-lg"></i> 聊天室</a></li>
                        <li>
                            <a href="{% url 'users:mail_inbox' %}"><i class="fa fa-envelope fa-lg"></i> 邮箱</a></li>
                        <li class="dropdown">
                            <a id="nickname" class="dropdown-toggle" data-toggle="dropdown"
                                href="{% url 'users:personal_index' request.user.id %}"
                                style="background-color:#337ab7">
                                {% ifequal user|getVerifyStatus False %}
                                (未学生验证)
                                {% endifequal %}
                                {% if user.user.profile %}
                                <img src="{{user.user.profile.url}}" height="30px" style="margin:-10px 0px;">
                                {% else %}
                                <img src="{% static '/img/default.jpg' %}" height="30px" style="margin:-10px 0px;">
                                {% endif %}
                                <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'commodity:commodity_repertory' %}"><i class="fa fa-edit fa-lg"></i>&nbsp;&nbsp;&nbsp;&nbsp;商品管理</a></li>
                                <li><a href="{% url 'users:settings' %}"><i class="fa fa-user-circle fa-lg"></i>&nbsp;&nbsp;&nbsp;&nbsp;个人信息</a></li>
                                <li><a href="{% url 'users:reset_pwd' %}"><i class="fa fa-key fa-lg"></i>&nbsp;&nbsp;&nbsp;&nbsp;修改密码</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:logout' %}"><i class="fa fa-sign-out fa-lg"></i>&nbsp;&nbsp;&nbsp;&nbsp;登出</a></li>
                            </ul>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li id="login_button" style="background-color:#337ab7"><a href="{% url 'users:login' %}"><i class="fa fa-sign-in"></i> 登录</a>
                        </li>
                        <li id="reg_button" style="background-color:#337ab7"><a href="{% url 'users:register' %}">注册</a>
                        </li>
                    </ul>
                    {% endif %}
                    </ul>
                </div>
            </nav>
    </div>
    <!-- End Header Area -->
    </section>

    <!-- 距顶部搜索栏空间由margin-top控制 -->
    <div id="bg2" class="container" style="padding: 15px; height:100%; min-height:920px; margin:60px 0px 0px 5px;background-image: url({% static 'img/bg2.png' %});">
        <div>
            {% block content %}{% endblock %}
        </div>
    </div>


    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

home/templates/home/developing.html
<!DOCTYPE html>

{% extends "home/base.html" %} {% block title %} Index {% endblock %} {% load static %} {% block content %}

<html lang="zxx" class="no-js">

<body>
    <section class="project-area section-gap" id="project" style="padding-top: 50px">
        <div class="container">
            <div class="title text-center">
                <h1 class="mb-10">AntMark keep on developing ~ </h1>
            </div>
        </div>
    </section>
</body>

</html>

{% endblock content %}

home/templates/home/index.html
<!DOCTYPE html> {% extends "home/base.html" %} {% block title %} Index {% endblock %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<body class="overlay" style="background: rgba(0,0,0,.3);">
    <div class="banner-content text-center" style="margin:20% auto;">
        <img src="{% static '/img/logo.png' %}" alt="" height="150" style="margin-top: -100px;">
        <h3 class="text-black mb-20">大学生闲置物品交易平台</h3>
        <a href="{% url 'commodity:commodity_list' %}" class="header-btn">AntMark</a>
    </div>
</body>

<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $("#navbar").css("background-color", "rgba(0,0,0,.0001)");
        $("#login_button").css("background-color", "rgba(0,0,0,.0001)");
        $("#reg_button").css("background-color", "rgba(0,0,0,.0001)");
        $("#mailbox").css("background-color", "rgba(0,0,0,.0001)");
        $("#nickname").css("background-color", "rgba(0,0,0,.0001)");
        $("#navbar").css("opacity","0");
        $("#bg2").css("background-image","none");
    });
</script>
{% endblock content %}