AntMark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')), 
    path('users/', include('users.urls', namespace = 'users')),
    path('admin_manage/', include('admin_manage.urls', namespace = "admin_manage")),
    path('commodity/', include('commodity.urls', namespace = "commodity")),
    path('chatroom/',include('chatroom.urls', namespace = "chatroom")),
    path('ueditor/',include('DjangoUeditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\

commodity/urls.py
from django.urls import path, re_path
from . import views

app_name = "commodity"
urlpatterns = [
    path('commodity-list/', views.commodity_list, name = "commodity_list"),
    path('commodity-detail/<int:commodity_id>/', views.commodity_detail, name = "commodity_detail"),
    path('search-commodity/', views.search_commodity, name = "search_commodity"),
    
    path('commodity-repertory/', views.commodity_repertory, name = "commodity_repertory"),
    path('edit-commodity/<int:commodity_id>/', views.edit_commodity, name = "edit_commodity"),
    path('preview-commodity/<int:commodity_id>/', views.preview_commodity, name = "preview_commodity"),
    path('create-commodity/', views.create_commodity, name = "create_commodity"),
    path('del-commodity/', views.del_commodity, name = "del_commodity"),
    path('put-on-shelves-list/', views.put_on_shelves_list, name = "put_on_shelves_list"),
    path('put-off-shelves-list/', views.put_off_shelves_list, name = "put_off_shelves_list"),
    path('put-off-commodity/', views.put_off_commodity, name = "put_off_commodity"),
    path('put-on-commodity/', views.put_on_commodity, name = "put_on_commodity"),
    path('not-verified-list/', views.not_verified_list, name = "not_verified_list"),
    path('commodity-verify/', views.commodity_verify, name="commodity_verify"),
    path('commodity-image/<int:commodity_id>/', views.commodity_image, name = "commodity_image"),
]

home/urls.py
from django.urls import path
import django.views

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name = 'index'),
    
    path('annos/', views.annos, name = 'annos'),

    path('about/', views.about, name = 'about'),
]

commodity/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from DjangoUeditor.models import UEditorField

# 商品标签
class CommodityTag(models.Model):
	tag = models.CharField(max_length = 300)

	def __str__(self):
		return self.tag

# 商品货源
class CommoditySource(models.Model):
	source = models.CharField(max_length = 300)
	
	def __str__(self):
		return self.source

# 商品
class Commodity(models.Model):
	title = models.CharField(max_length = 300)
	owner = models.ForeignKey(User, related_name = "commodity", on_delete = models.CASCADE)
	commodity_tag = models.ForeignKey(CommodityTag, related_name = "commodity_tag", on_delete = models.CASCADE)
	commodity_source = models.ForeignKey(CommoditySource, related_name = "commodity_source", on_delete = models.CASCADE)
	body = UEditorField(verbose_name = "commodity_descriprion",imagePath="ueditorImages/", 
			width=700, height=600, filePath='ueditorFiles/', toolbars="full", 
			upload_settings={"imageMaxSize":1204000}, blank = True)
	price = models.DecimalField(max_digits=7, decimal_places=2, default = 0.00)
	image = models.ImageField(blank=True)
	for_sale = models.BooleanField(default = True)
	is_verified = models.BooleanField(default = True)
	created = models.DateTimeField(default = timezone.now)
	updated = models.DateTimeField(auto_now = True)

	class Meta:
		ordering = ('-updated',)

	def __str__(self):
		return self.title

commodity/forms.py
from django import forms

from .models import CommodityTag, Commodity, CommoditySource

class CommodityTagForm(forms.ModelForm):
    class Meta:
        model = CommodityTag
        fields = ('tag', )

class CommoditySourceForm(forms.ModelForm):
    class Meta:
        model = CommoditySource
        fields = ('source', )


class CommodityForm(forms.ModelForm):
    class Meta:
        model = Commodity
        fields = ('title', 'body', 'price')

commodity/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.urls import reverse
from django.contrib.auth.models import User

import sys
sys.path.append('..')
from users.models import Message, UserInfo
from AntMark import settings

from .models import CommodityTag, Commodity, CommoditySource
from .forms import CommodityTagForm, CommodityForm, CommoditySourceForm
from helper.decorator import user_verify_required


# 显示所有商品
@login_required(login_url = '/users/login')
@csrf_exempt
def commodity_list(request):
    commodity_list = Commodity.objects.filter(is_verified = True, for_sale = True)
    paginator = Paginator(commodity_list, 20)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        commodities = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        commodities = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(1)
        commodities = current_page.object_list
    sources = CommoditySource.objects.all()
    context = {'commodities':commodities, 'page':current_page, 'sources':sources}
    return render(request, 'commodity/common/commodity_list.html', context)


# 显示商品详情
@login_required(login_url = '/users/login')
@csrf_exempt
def commodity_detail(request, commodity_id):
    commodity = get_object_or_404(Commodity, id = commodity_id)
    if commodity.is_verified and commodity.for_sale :
        similar_commodities = Commodity.objects.filter(commodity_tag = commodity.commodity_tag, for_sale = True, is_verified = True).exclude(id = commodity.id)
        similar_commodities = similar_commodities[:4]
        context = {"commodity":commodity, "similar_commodities":similar_commodities}
        return render(request, "commodity/common/commodity_detail.html", context)
    else:
        return render_to_response('404.html')


# 个人商品库
@login_required(login_url = '/users/login')
@csrf_exempt
@user_verify_required
def commodity_repertory(request):
    commodity_list = Commodity.objects.filter(owner = request.user, is_verified = True)
    paginator = Paginator(commodity_list, 16)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        commodities = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        commodities = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(1)
        commodities = current_page.object_list
    context = {'commodities':commodities, 'page':current_page}
    return render(request, 'commodity/personal/commodity_repertory.html', context)

# 创建商品
@login_required(login_url = '/users/login')
@csrf_exempt
@user_verify_required
def create_commodity(request):
    if request.method == 'POST':
        commodity_form = CommodityForm(data = request.POST)
        if commodity_form.is_valid():
            cd = commodity_form.cleaned_data
            try:
                tag = CommodityTag.objects.get(tag = request.POST['tag'])
                source = CommoditySource.objects.get(source = request.POST['source'])
                commodity = Commodity.objects.create(owner=request.user, commodity_source = source, commodity_tag = tag)
                
                commodity.title = cd['title']
                commodity.body = cd['body']
                commodity.price = cd['price']
                commodity.for_sale = False
                commodity.is_verified = False
                commodity.save()
                # 重定向
                return HttpResponseRedirect(reverse('commodity:not_verified_list'))
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        commodity_form = CommodityForm()
        tags = CommodityTag.objects.all()
        sources = CommoditySource.objects.all()
        context = {'commodity_form':commodity_form, 'tags':tags, 'sources':sources}
        return render(request, 'commodity/personal/create_commodity.html', context)


# 编辑商品信息
@login_required(login_url = '/users/login')
@csrf_exempt
@user_verify_required
def edit_commodity(request, commodity_id):
    commodity = get_object_or_404(Commodity, id = commodity_id)
    if request.method == 'GET':
        commodity_form = CommodityForm()
        sources = CommoditySource.objects.all()
        tags = CommodityTag.objects.all()
        context = {'commodity':commodity, 'commodity_form':commodity_form, 'sources':sources, 'tags':tags}
        return render(request, 'commodity/personal/edit_commodity.html', context)
    else:
        commodity_form = CommodityForm(data = request.POST)
        if commodity_form.is_valid():
            cd = commodity_form.cleaned_data
            try:
                tag = CommodityTag.objects.get(tag = request.POST['tag'])
                source = CommoditySource.objects.get(source = request.POST['source'])
                commodity.title = cd['title']
                commodity.price = cd['price']
                commodity.body = cd['body']
                commodity.commodity_tag = tag
                commodity.commodity_source =  source
                commodity.is_verified = False
                commodity.for_sale = False

                commodity.save()
                return HttpResponseRedirect(reverse('commodity:not_verified_list'))
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")

# 上传商品图像
@login_required(login_url = '/users/login')
@csrf_exempt
@user_verify_required
def commodity_image(request, commodity_id):
    if request.method == 'POST':
        img = request.POST['img']
        commodity = Commodity.objects.get(id=commodity_id) 
        commodity.image = img
        commodity.save()
        return HttpResponse("1")
    else:
        context = {'commodity_id':commodity_id}
        return render(request, 'commodity/personal/imagecrop.html', context)

# 删除商品
@login_required(login_url = '/users/login')
@require_POST
@csrf_exempt
@user_verify_required
def del_commodity(request):
    commodity_id = request.POST['commodity_id']
    try:
        commodity = Commodity.objects.get(id = commodity_id)
        commodity.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

# 预览商品
@login_required(login_url = '/users/login')
@csrf_exempt
@user_verify_required
def preview_commodity(request, commodity_id):
    commodity = get_object_or_404(Commodity, id = commodity_id)
    similar_commodities = Commodity.objects.filter(commodity_tag = commodity.commodity_tag, for_sale = True, is_verified = True).exclude(id = commodity.id)
    similar_commodities = similar_commodities[:4]
    context = {"commodity":commodity, "similar_commodities":similar_commodities}
    return render(request, "commodity/personal/preview_commodity.html", context)


# 待上架的商品列表
@login_required(login_url = '/users/login')
@csrf_exempt
@user_verify_required
def put_on_shelves_list(request):
    commodity_list = Commodity.objects.filter(owner = request.user, for_sale = False, is_verified = True)
    paginator = Paginator(commodity_list, 16)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        commodities = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        commodities = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(1)
        commodities = current_page.object_list    
    context = {'commodities':commodities, 'page':current_page}
    return render(request, 'commodity/personal/put_on_shelves_list.html', context)

# 将商品库的商品上架
@login_required(login_url = '/users/login')
@require_POST
@csrf_exempt
@user_verify_required
def put_on_commodity(request):
    commodity_id = request.POST['commodity_id']
    try:
        commodity = Commodity.objects.get(id = commodity_id)
        commodity.for_sale = True
        commodity.save()
        return HttpResponse("1")
    except:
        return HttpResponse('2')

# 正在上架的商品列表
@login_required(login_url = '/users/login')
@csrf_exempt
@user_verify_required
def put_off_shelves_list(request):
    commodity_list = Commodity.objects.filter(owner = request.user, for_sale = True, is_verified = True)
    paginator = Paginator(commodity_list, 16)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        commodities = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        commodities = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(1)
        commodities = current_page.object_list
    context = {'commodities':commodities, 'page':current_page}
    return render(request, 'commodity/personal/put_off_shelves_list.html', context)

# 将商品下架
@login_required(login_url = '/users/login')
@require_POST
@csrf_exempt
@user_verify_required
def put_off_commodity(request):
    commodity_id = request.POST['commodity_id']
    try:
        commodity = Commodity.objects.get(id = commodity_id)
        commodity.for_sale = False
        commodity.save()
        return HttpResponse("1")
    except:
        return HttpResponse('2')

# 未通过审核商品列表
@login_required(login_url = '/users/login')
@csrf_exempt
@user_verify_required
def not_verified_list(request):
    commodity_list = Commodity.objects.filter(owner = request.user, is_verified = False)
    paginator = Paginator(commodity_list, 16)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        commodities = current_page.object_list
    except PageNotAnInteger:

commodity/templates/commodity/personal/commodity_repertory.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block content %}

<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/commodity.css' %}">

<div class='container'>
    {% include 'commodity/upslider.html' %}
    <br>
    <div style="margin-bottom: 15px;">
        <span style="color:rgb(238, 22, 87);font-weight: bolder;">说明: 审核通过的商品会置于商品库中，包括已上架和未上架的商品，您可以对商品再次进行修改和删除。
            在修改了商品信息后，该商品将会处于未审核状态，由管理员通过审核后才能将被上架。请谨慎修改商品信息。</span>
    </div>
    <div class="row clearfix">
        {% for commodity in commodities %}{% if commodity.is_verified %}
        <div style="display:inline-block;">
            <div class="single-feature mb-30" style="width:262px; margin-right:12px;">
                {% if commodity.image %}
                <img src="{{ commodity.image | striptags }}" height="200px" class="center-block">
                {% else %}
                <img src="{% static 'img/defaultImage.jpg' %}" height="200px" class="center-block">
                {% endif %}
                <div class="title d-flex flex-row pb-20">
                    <span class="glyphicon glyphicon-gift"></span>
                    <h5 id="line-limit-length">{{commodity.title}}</h5>
                </div>
                <p id="line-limit-length">待售：{{commodity.for_sale}}</p>
                <p id="line-limit-length">标签：{{commodity.commodity_tag}}</p>
                <p id="line-limit-length">货源：{{commodity.commodity_source}}</p>
                <p id="line-limit-length">价格：￥{{commodity.price}}</p>
                <a name="preview" href="{% url 'commodity:preview_commodity' commodity.id %}">
                    <button type="button" class="btn btn-info">预览</button>
                </a>
                <a name="edit" href="{% url 'commodity:edit_commodity' commodity.id %}">
                    <button type="button" class="btn btn-info" style="margin-left:10px">编辑</button>
                </a>
                <a name="delete" href="javascript:" onclick="del_commodity(this, {{commodity.id}})">
                    <button type="button" class="btn btn-danger" style="margin-left:10px">删除</button>
                </a>
            </div>
        </div>
        {% endif %}
        {% empty %}
        <div style="text-align: center;">
            <img src="{% static 'img/noVerifiedCommodity.png' %}" width="60%">
        </div>
        {% endfor %}
    </div>
    {% include 'paginator.html' %}
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/layer.js' %}"></script>
<script src="{% static 'js/json2.js' %}"></script>
<script type="text/javascript">
    function del_commodity(the, commodity_id) {
        var commodity_name = $(the).parents("div").children("div").children("h4").text();
        // var commodity_name = $(the).parents("div").children("h4").text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除商品",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除商品：' + commodity_name +
                '</p> </div>',
            btn: ['确定', '取消'],
            yes: function () {
                $.ajax({
                    url: '{% url "commodity:del_commodity" %}',
                    type: "POST",
                    data: {
                        "commodity_id": commodity_id
                    },
                    success: function (e) {
                        if (e == "1") {
                            parent.location.reload();
                            layer.msg("已删除");
                        } else {
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }
</script>
<script>
    var temp = document.getElementById("upslider1");
    temp.classList.add("active");
</script>
{% endblock %}

commodity/templates/commodity/personal/create_commodity.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}"> 
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">

<div class='container'>
    {% include 'commodity/upslider.html' %}
    <br>
    <div style="margin-bottom: 15px;">
        <span style="color:rgb(238, 22, 87);font-weight: bolder;">说明: 创建商品时请填写完整的信息，商品封面可在创建商品后点击“编辑”添加。</span>
    </div>
    <div style="margin-left:10px">
        <form class="form-horizontal" enctype="multipart/form-data" action="{% url 'commodity:create_commodity' %}" method="post">{% csrf_token %} 
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>商品名称:</span></div>
                <div class="col-md-10 text-left"><input type="text" name="title" required style="width:400px"></div> 
            </div>
            <div class="row" style="margin-top: 10px">
                <div class="col-md-2 text-right"><span>商品标签:</span></div>
                <div class="col-md-10 text-left">  
                    <select name="tag" required >
                        {% for tag in tags %}
                        <option id="{{tag.id}}" name="tag" value="{{tag.tag}}">{{tag.tag}}</option>
                        {% empty %}
                        {% endfor %}                     
                    </select>
                </div>
            </div>
            <div class="row" style="margin-top: 10px">
                <div class="col-md-2 text-right"><span>商品货源:</span></div>
                <div class="col-md-10 text-left">
                    <select name="source" required>
                        {% for source in sources %}
                        <option id="{{source.id}}" name="source" value="{{source.source}}">{{source.source}}</option>
                        {% empty %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>商品价格:</span></div>
                <div class="col-md-10 text-left"><input type="number" name="price" min="0" max="10000" step="0.01" required style="width:80px"> 元</div> 
            </div>
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>商品描述:</span></div>
                <div id="editormd" class="col-md-10 text-left">
                    <script id="container" name="body" type="text/platin" required></script>
                </div> 
            </div>  
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"></div>
                <div class="col-md-10 text-left"><span style="color:red">注：在创建商品成功后，请点击“编辑”上传商品封面，否则无法通过审核</span></div>
            </div>       
            <div class="row" style="margin:10px 0px 0px 190px">
                <div class="col-md-2 text-left">
                    <input type="submit" class="btn btn-info btn-lg" value="提交" onclick="create_commodity()">
                </div>
                <div class="col-md-2 col-md-offset-6 text-left">
                    <input type="button" class="btn btn-danger btn-lg" onclick="cancel()" value="取消">
                </div>
            </div>
        </form>
    </div>
</div>




<script src="{% static '/ueditor/ueditor.config.js' %}" type="text/javascript"></script>
<script src="{% static '/ueditor/ueditor.all.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/layer.js' %}"></script>
<script src="{% static 'js/json2.js' %}"></script>
<script language="javascript"> 
//js函数实现富文本编辑器 
var ue = UE.getEditor('container',{
    initialFrameWidth: 720,
    initialFrameHeight: 500,
    serverUrl:'/ueditor/controller/?imagePathFormat=ueditorImages/&filePathFormat=ueditorFiles/',
});

function cancel(){
    if(confirm("您确定要关闭本页面吗？")){
        window.history.back(-1); 
    }
}

//写js函数create_commodity()实现提交表单功能，上面出现的所有字段都要提交
function create_commodity(){
    var title = $("#id_title").val();
    var body = $("#id_body").val();
    var price = $("#id_price").val();
    var tags = [];
    $.each($("input[name='tag']:checked"), function(){tags.push($(this).val());});
    $.ajax({
        url: "{% url 'commodity:not_verified_list' %}",
        type: "POST",
        data: {"title":title, "body":body, "price":price, "tags":JSON.stringify(tags)},
        // async: false,
        success: function(e){
            if(e=="2"||e=="3"){
                layer.msg("请检查填写的商品信息！");
            }
        },
    });
}   

var temp = document.getElementById("upslider2");
temp.classList.add("active");
</script>
{% endblock %}

commodity/templates/commodity/personal/not_verified_list.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/commodity.css' %}">
<div class="container">
    {% include 'commodity/upslider.html' %}
    <br>
    <div style="margin-bottom: 15px;">
        <span style="color:rgb(238, 22, 87);font-weight: bolder;">说明: 以下是您创建后未通过审核的商品，您可以对商品信息进行修改。
        点击“提交”之后，该商品信息会被系统提交给管理员，管理员通过审核之后商品会出现在您的商品仓库中，由您选择上架或下架。
        若审核未通过，系统将提示您该商品未通过审核的原因，您可以继续修改商品信息后再“提交”。</span>
    </div>
    <div class="row clearfix">
        {% for commodity in commodities %}
        <div style="display:inline-block;">
            <div class="single-feature mb-30" style="width:262px; margin-right:12px;">
                {% if commodity.image %}
                <img src="{{commodity.image | striptags}}" height="200px" class="center-block">
                {% else %}
                <img src="{% static 'img/defaultImage.jpg' %}" height="200px" class="center-block">
                {% endif %}
                <div class="title d-flex flex-row pb-20">
                    <span class="glyphicon glyphicon-gift"></span>
                    <h5 id="line-limit-length"><a href="{% url 'commodity:commodity_detail' commodity.id %}">{{commodity.title}}</a></h5>
                </div>
                <p id="line-limit-length">待售：{{commodity.for_sale}}</p>
                <p id="line-limit-length">标签：{{commodity.commodity_tag}}</p>
                <p id="line-limit-length">货源：{{commodity.commodity_source}}</p>
                <p id="line-limit-length">价格：￥{{commodity.price}}</p>
                <a name="preview" href="{% url 'commodity:preview_commodity' commodity.id %}">
                    <button type="button" class="btn btn-info btn-sm">预览</button>
                </a>
                <a name="edit" href="{% url 'commodity:edit_commodity' commodity.id %}">
                    <button type="button" class="btn btn-info btn-sm">编辑</button>
                </a>
                <a name="delete" href="javascript:" onclick="del_commodity(this, {{commodity.id}})">
                    <button type="button" class="btn btn-danger btn-sm">删除</button>
                </a>

                <a name="verify" href="javascript:" onclick="verify_commodity(this, {{commodity.id}})">
                    <button type="button" class="btn btn-success btn-sm">提交</button>
                </a>   
            </div>
        </div>
        {% empty %}
        <div style="text-align: center;">
            <img src="{% static 'img/allVerified.png' %}" width="60%">
        </div>
        {% endfor %}
    </div>
    {% include 'paginator.html' %}
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/layer.js' %}"></script>
<script src="{% static 'js/json2.js' %}"></script>
<script type="text/javascript">
    function del_commodity(the, commodity_id) {
        var commodity_name = $(the).parents("div").children("div").children("h4").text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除商品",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除商品' + commodity_name +
                '</p> </div>',
            btn: ['确定', '取消'],
            yes: function () {
                $.ajax({
                    url: '{% url "commodity:del_commodity" %}',
                    type: "POST",
                    data: {
                        "commodity_id": commodity_id
                    },
                    success: function (e) {
                        if (e == "1") {
                            parent.location.reload();
                            layer.msg("已删除");
                        } else {
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }
</script>
<script type="text/javascript">
    function verify_commodity(the, commodity_id) {
        var commodity_name = $(the).parents("div").children("div").children("h4").text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "提交审核",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定将该商品提交审核' + commodity_name +
                '</p> </div>',
            btn: ['确定', '取消'],
            yes: function () {
                $.ajax({
                    url: '{% url "commodity:commodity_verify" %}',
                    type: "POST",
                    data: {
                        "commodity_id": commodity_id
                    },
                    success: function (e) {
                        if (e == "1") {
                            layer.msg("提交成功，请等待管理员审核",{time:1300}, function(){location.href='{% url "commodity:not_verified_list" %}'});
                            
                        } else {
                            layer.msg("提交失败，请重试", {time:1300}, function(){location.href='{% url "commodity:not_verified_list" %}'});
                        }
                    },
                })
                return false;
            },
        });
    }
</script>
<script>
    var temp = document.getElementById("upslider5");
    temp.classList.add("active");
</script>
{% endblock %}

commodity/templates/commodity/personal/put_off_shelves_list.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/commodity.css' %}">
<div class="container">
    {% include 'commodity/upslider.html' %}
    <br>
    <div style="margin-bottom: 15px;">
        <span style="color:rgb(238, 22, 87);font-weight: bolder;">说明: 以下是您已上架的商品，您可以点击“下架”将某一商品下架。
            下架后的商品将不会出现在商品列表中，用户也无法搜索到该商品。</span>
    </div>
    <div class="row clearfix">
        {% for commodity in commodities %}
        <div style="display:inline-block;">
            <div class="single-feature mb-30" style="width:262px; margin-right:12px;">
                {% if commodity.image %}
                <img src="{{commodity.image | striptags}}" height="200px" class="center-block">
                {% else %}
                <img src="{% static 'img/defaultImage.jpg' %}" height="200px" class="center-block">
                {% endif %}
                <div class="title d-flex flex-row pb-20">
                    <span class="glyphicon glyphicon-gift"></span>
                    <h5 id="line-limit-length">{{commodity.title}}</h5>
                </div>
                <p id="line-limit-length">待售：{{commodity.for_sale}}</p>
                <p id="line-limit-length">标签：{{commodity.commodity_tag}}</p>
                <p id="line-limit-length">货源：{{commodity.commodity_source}}</p>
                <p id="line-limit-length">价格：￥{{commodity.price}}</p>
                <a name="preview" href="{% url 'commodity:preview_commodity' commodity.id %}">
                    <button type="button" class="btn btn-info">预览</button>
                </a>
                <input type="button" class="btn btn-info" href="javascript:" id="test2" value="下架" onclick="put_off(this, {{commodity.id}})">
            </div>
        </div>
        {% empty %}
        <div style="text-align: center;">
            <img src="{% static 'img/allPutOff.png' %}" width="60%">
        </div>
        {% endfor %}
    </div>
    {% include 'paginator.html' %}
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/layer.js' %}"></script>
<script src="{% static 'js/json2.js' %}"></script>
<script type="text/javascript">
    function put_off(the, commodity_id) {
        $.ajax({
            url: "{% url 'commodity:put_off_commodity' %}",
            type: "POST",
            data: {
                "commodity_id": commodity_id
            },
            success: function (e) {
                if (e == "1") {
                    layer.msg("下架成功");
                    location.href = "{% url 'commodity:put_off_shelves_list' %}";
                } else {
                    layer.msg("下架失败.");
                }
            },
        });
    }
</script>
<script>
    var temp = document.getElementById("upslider4");
    temp.classList.add("active");
</script>
{% endblock %}