AntMark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')), 
    path('users/', include('users.urls', namespace = 'users')),
    path('admin_manage/', include('admin_manage.urls', namespace = "admin_manage")),
    path('commodity/', include('commodity.urls', namespace = "commodity")),
    path('chatroom/',include('chatroom.urls', namespace = "chatroom")),
    path('ueditor/',include('DjangoUeditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\

commodity/urls.py
from django.urls import path, re_path
from . import views

app_name = "commodity"
urlpatterns = [
    path('commodity-list/', views.commodity_list, name = "commodity_list"),
    path('commodity-detail/<int:commodity_id>/', views.commodity_detail, name = "commodity_detail"),
    path('search-commodity/', views.search_commodity, name = "search_commodity"),
    
    path('commodity-repertory/', views.commodity_repertory, name = "commodity_repertory"),
    path('edit-commodity/<int:commodity_id>/', views.edit_commodity, name = "edit_commodity"),
    path('preview-commodity/<int:commodity_id>/', views.preview_commodity, name = "preview_commodity"),
    path('create-commodity/', views.create_commodity, name = "create_commodity"),
    path('del-commodity/', views.del_commodity, name = "del_commodity"),
    path('put-on-shelves-list/', views.put_on_shelves_list, name = "put_on_shelves_list"),
    path('put-off-shelves-list/', views.put_off_shelves_list, name = "put_off_shelves_list"),
    path('put-off-commodity/', views.put_off_commodity, name = "put_off_commodity"),
    path('put-on-commodity/', views.put_on_commodity, name = "put_on_commodity"),
    path('not-verified-list/', views.not_verified_list, name = "not_verified_list"),
    path('commodity-verify/', views.commodity_verify, name="commodity_verify"),
    path('commodity-image/<int:commodity_id>/', views.commodity_image, name = "commodity_image"),
]

home/urls.py
from django.urls import path
import django.views

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name = 'index'),
    
    path('annos/', views.annos, name = 'annos'),

    path('about/', views.about, name = 'about'),
]

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    # 基础功能
    path('login/', views.login_view, name = 'login'),

    path('logout/', views.logout_view, name = 'logout'),

    path('register/', views.user_reg, name = 'register'),

    path('active/<str:active_code>', views.user_active, name = 'active'),

    path('settings/', views.user_settings, name = 'settings'),

    path('reset_pwd/', views.reset_password, name = 'reset_pwd'),

    path('personal_index/<int:user_id>', views.personal_index, name = 'personal_index'),

    path('stu_verify/', views.stu_verify, name = 'stu_verify'),

    
    # 消息处理相关
    path('mail_inbox/', views.mail_inbox, name = 'mail_inbox'),

    path('mail_outbox/', views.mail_outbox, name = 'mail_outbox'),

    path('call_admin/', views.call_admin, name = 'call_admin'),

    path('send_message/<int:user_id>', views.send_message, name = 'send_message'),

    path('set_as_read/<int:message_id>', views.set_as_read, name = 'set_as_read'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('del_message/<int:message_id>', views.del_message, name = 'del_message'),

    path('deal_mult_msg/', views.deal_mult_msg, name = 'deal_mult_msg'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.

class UserInfo(models.Model):
    GENDER_CHOICES = (
        (u'M', u'Male'),
        (u'F', u'Female'),
    )
    user = models.OneToOneField(User, on_delete = models.CASCADE, related_name="user")
    nickname = models.CharField(max_length=20, default="None")
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default="Male")
    intro = models.CharField(max_length=200, default="None")
    phone = models.CharField(max_length=15, default="0")
    wechat = models.CharField(max_length=30, default="None")
    qq = models.CharField(max_length=16, default="0")
    profile = ProcessedImageField(upload_to='user/img', default='user/img/default.jpg', 
        processors=[ResizeToFill(500, 500)],  format='JPEG', options={'quality': 60})
    is_verified = models.BooleanField(default=False)
    stuCardPhoto = ProcessedImageField(upload_to='user/img/verify', null=True, format='JPEG')
    
    def __str__(self):
        return self.nickname + " " + str(self.user)


class Message(models.Model):
    TYPE_CHOICES = (
        (u'M', u'massage'),
        (u'S', u'stu_verify'),
        (u'C', u'commodity_verify'),
    )
    sender = models.ForeignKey(User, related_name="sender_msg", on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name="receiver_msg", on_delete=models.CASCADE)
    msg_type = models.CharField(max_length=20, choices=TYPE_CHOICES, default="message")
    text = models.CharField(max_length=2000)
    id_content = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    sender_del = models.BooleanField(default=False)
    receiver_del = models.BooleanField(default=False)
    
    def __str__(self):
        return self.text

users/forms.py
from django import forms
#from markdown import MarkdownFormField
from users.models import UserInfo


#class ProfileForm(forms.Form):
 #   upProfile = forms.FileField()

class InfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = [
            'nickname',
            'gender',
            'intro',
            'phone',
            'wechat',
            'qq',
        ]
        labels = {
            'nickname': '昵称',
            'gender': '性别',
            'intro': '个人简介',
            'phone': '电话',
            'wechat': '微信',
            'qq': 'QQ',
        }

users/views.py
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404, HttpResponse

from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password, check_password

from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import EmailMultiAlternatives, send_mail

from django.db.models import Q

from helper.crypto import encrypt, decrypt
from django.conf import settings

from users.models import UserInfo, Message
from users.forms import InfoForm
from commodity.models import Commodity

import re, time, json

def login_view(request):
    """ 用户登录 """
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home:index'))
    if request.method != 'POST':
        form = AuthenticationForm(request)
    else:
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return HttpResponseRedirect(reverse('home:index'))
    context = { 'form': form }
    return render(request, 'users/login.html', context)


def logout_view(request):
    """ 用户登出 """
    logout(request)
    return HttpResponseRedirect(reverse('home:index'))


def get_active_code(email):
    """ 利用时间及邮箱获取激活码 """
    key = 9
    encry_str = '%s|%s' % (email,time.strftime('%Y-%m-%d',time.localtime(time.time())))
    active_code = encrypt(key, encry_str)
    return active_code


def send_active_email(email, active_code):
    """ 发送激活邮件 """
    url = settings.CUR_HOST + 'users/active/' + active_code
    subject = '[AntMark]激活你的账号'
    message = '''
        <h2> <a href=''' + settings.CUR_HOST + ''' target=_blank> AntMark.com </a> </h2>
        <br/>
        <p>点击下面的链接进行激活操作（7天后过期）<a href="%s" target=_balnk> AntMark激活链接 </a></p>
    ''' % url

    send_mail(subject, '', 'antmark_mail@sina.com', [email], fail_silently=False, html_message=message)
    
    
def user_reg(request):
    response_data = {}
    user_form = UserCreationForm()
    if request.method == 'POST':
        try:
            reg_name = request.POST['username']
            reg_pwd1 = request.POST['password1']
            reg_pwd2 = request.POST['password2']

            if len(reg_name) * len(reg_pwd1) * len(reg_pwd2) == 0:
                raise Exception('邮箱或密码为空')
            
            #匹配邮箱格式
            pattern = re.compile(r'^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$')
            match = pattern.match(reg_name)
            if not match:
                raise Exception('请使用邮箱作为用户名，邮箱格式错误')

            pattern = re.compile(r'^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,16}$')
            match = pattern.match(reg_pwd1)
            if not match:
                raise Exception("密码必须包含大小写字母和数字的组合，可以使用除'.'之外的特殊字符，长度在8-16之间")

            if '.' in reg_pwd1:
                raise Exception('密码不合法，换一个试试？')

            # 判断用户名是否已经被注册
            user = User.objects.filter(username=reg_name)
            if len(user) > 0:
                raise Exception('该邮箱已被注册')
            
            if reg_pwd1 != reg_pwd2:
                raise Exception('两次输入的密码不一致')

            user_form = UserCreationForm(data=request.POST)
            # if user_form.is_valid():
            new_user = user_form.save()
            new_user.email = reg_name
            new_user.is_active = False
            new_user.save()

            response_data['success'] = True
            response_data['message'] = '注册成功，已发送激活邮件到你的邮箱，请前往激活'
            
        except Exception as e:
            response_data['success'] = False
            response_data['message'] = str(e)
        
        finally:
            if response_data['success']:
                try:
                    active_code = get_active_code(reg_name)
                    send_active_email(reg_name, active_code)
                except Exception as e:
                    response_data['message'] = '发送激活邮件失败，请稍后重新注册' + str(e)
                    new_user.delete()
                    
                response_data['goto_url'] = settings.CUR_HOST + 'users/login'
                response_data['goto_time'] = 5
                response_data['next_page'] = "用户登录界面"
                return render(request, 'users/notice.html', response_data)
    
    context = { 
        'user_form': user_form, 
        'response_data': response_data,
    }
    return render(request, 'users/register.html' , context)


def user_active(request, active_code):
    """ 激活用户 """
    # 加错误处理，避免出错。出错认为激活链接失效
    # 解密激活链接
    key, response_data = 9, {}
    try:
        decrypt_str = decrypt(key,active_code)
        decrypt_data = decrypt_str.split('|')
        email = decrypt_data[0]                                     #邮箱
        create_date = time.strptime(decrypt_data[1], "%Y-%m-%d")    #激活链接创建日期
        create_date = time.mktime(create_date)                      #struct_time 转成浮点型的时间戳
 
        day = int((time.time()-create_date)/(24*60*60))             #得到日期差
        if day > 7:
            raise Exception(u'激活链接过期')
 
        #激活
        user = User.objects.filter(username=email)
        if len(user) == 0:
            raise Exception(u'激活链接无效')
        else:
            user = User.objects.get(username=email)
 
        if user.is_active:
            raise Exception(u'该帐号已激活过了')

        else:
            user.is_active = True
            user.save()
            # 在确认用户账号激活成功后及时创建用户信息表
            UserInfo.objects.create(user=user)
            
 
        response_data['goto_page'] = True
        response_data['message'] = '激活成功，欢迎加入AntMark！'

    except IndexError as e:
        response_data['goto_page'] = False
        response_data['message'] = '激活链接无效'
    
    except Exception as e:
        response_data['goto_page'] = False
        response_data['message'] = str(e)
    
    finally:
        #激活成功就跳转到首页(message页面有自动跳转功能)
        response_data['goto_url'] = settings.CUR_HOST + 'users/login'
        response_data['goto_time'] = 5
        response_data['next_page'] = "用户登录界面"

        return render(request, 'users/notice.html' , response_data)


@login_required
def user_settings(request):
    if request.method != 'POST':
        try:
            info = UserInfo.objects.get(user=request.user)
        except ObjectDoesNotExist:
            info = UserInfo.objects.create(user=request.user)
        info_form = InfoForm(instance=info)
        context = {
            'info_form': info_form,
            'info': info,
        }
        return render(request, 'users/settings.html' , context)
    else:
        info_form = InfoForm(data=request.POST)
        if info_form.is_valid():
            try:
                info = UserInfo.objects.get(user=request.user)
            except ObjectDoesNotExist:
                info = UserInfo.objects.create(user=request.user)
        info.nickname = info_form.cleaned_data["nickname"]
        info.gender = info_form.cleaned_data["gender"]
        info.intro = info_form.cleaned_data["intro"]
        info.phone = info_form.cleaned_data['phone']
        info.wechat = info_form.cleaned_data['wechat']
        info.qq = info_form.cleaned_data['qq']
        myprofile = request.FILES.get('profile', None)

        if myprofile:
            accept_format = ['png', 'jpg', 'peg'] #peg -> jpeg
            if myprofile.name[-3:] not in accept_format:
                response_data = {
                    'message': "提交的图片格式应该为 png/jpg/jpeg ",
                    'next_page': "用户设置页面",
                    'goto_url': settings.CUR_HOST + 'users/settings/', 
                    'goto_time': 3,
                }
                return render(request, 'users/notice.html' , response_data)
                
            if info.profile.name != 'user/img/default.jpg' :
                info.profile.delete()
            info.profile = myprofile
        info.save()
        return HttpResponseRedirect(reverse('home:index'))


@login_required
def reset_password(request):
    form = PasswordChangeForm(user=request.user)
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)

            response_data = {}
            response_data['message'] = '密码修改成功，返回主页面'
            response_data['goto_url'] = settings.CUR_HOST
            response_data['goto_time'] = 3

            return render(request, 'users/notice.html' , response_data)

    context = { 'form': form }
    return render(request, 'users/reset_pwd.html', context)


@login_required
def personal_index(request, user_id):
    cur_user = User.objects.get(id=user_id)
    cur_info = UserInfo.objects.get(user=cur_user)
    comms = Commodity.objects.filter(owner=cur_user)
    context = {
        'cur_user': cur_user,
        'cur_info': cur_info,
        'comms': comms,
    }
    return render(request, 'users/personal_index.html', context)


@login_required
def stu_verify(request):
    """ 用户提交校园卡照片，后台审核 """
    info = UserInfo.objects.get(user=request.user)
    response_data = {
        'message': "你已经完成学生认证啦，不用重复认证",
        'next_page': "用户设置页面",
        'goto_url': settings.CUR_HOST + 'users/settings/', 
        'goto_time': 3,
    }
    if info.is_verified:
        return render(request, 'users/notice.html' , response_data)

    if request.method == 'POST':
        stu_card_photo = request.FILES.get('stu_card_photo', None)

        accept_format = ['png', 'jpg', 'peg'] #peg -> jpeg
        if stu_card_photo.name[-3:] not in accept_format:
            response_data['message'] = "提交的图片格式应该为 png/jpg/jpeg "
            return render(request, 'users/notice.html' , response_data)

        if stu_card_photo:

users/templates/users/mail_inbox.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load staticfiles %} {% load bootstrap4 %} {% load base %} {% block content %}

<script>
    //选中收件箱中的所有邮件
    function select_all_recemsg() {
        var select_box = document.getElementById("rece_select_all")
        var boxs = document.getElementsByName("checkbox_list");
        var flag = select_box.checked
        for (var i = 0; i < boxs.length; i++) {
            boxs[i].checked = flag;
        }
    }

    //警告框
    function setAsRead() {
        event.returnValue = confirm("是否将已经选择的多条信息标记为已读？")
    }

    function delInboxMsgConfirm() {
        event.returnValue = confirm("是否从'收件箱中'删除已经选择的信息？")
    }
</script>

<body>
    <div class="section-top-border-new">
        <h1><i class="fa fa-envelope"></i> 收件箱</h1>
        <br/>
        <div style="float:right">
            <a href="{% url 'users:mail_inbox' %}" class="btn btn-success">收件箱</a>
            <a href="{% url 'users:mail_outbox' %}" class="btn btn-info">发件箱</a>
        </div>
        <br/>
        <div class="section" id="inbox">
            <form action="{% url 'users:deal_mult_msg' %}" enctype="multipart/form-data" method="POST" class="form">{% csrf_token %}
                <button type="submit" class="btn btn-info" name="delete_msg" onclick="delInboxMsgConfirm()">删除</button>
                <button type="submit" class="btn btn-info" name="set_as_read" onclick="setAsRead()">标记为已读</button><br/><br/>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="rece_select_all" onclick="select_all_recemsg()"></th>
                            <th>时间</th>
                            <th>发信人</th>
                            <th>信件内容</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in inbox_messages %} {% ifequal message.is_read False %}
                        <tr class="info">
                            <td><input type="checkbox" name="checkbox_list" value='{{message.id}}'></td>
                            <td>{{ message.timestamp|date:'M d, Y H:i' }}</td>
                            <td>{{ message.sender|getUserNickname }}({{ message.sender }})</td>
                            {% if message.text|length > 40 %}
                            <td>{{ message.text|slice:'0 : 40' }} . . .</td>
                            {% else %}
                            <td>{{ message.text}}</td>
                            {% endif %}
                            <td>
                                <a href="{% url 'users:read_message' message.id %}" title="查看并回复">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'users:set_as_read' message.id %}" title="标记为已读">
                                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                        {% else %}
                        <tr>
                            <td><input type="checkbox" name="checkbox_list" id="{{message.id}}" value="{{message.id}}"></td>
                            <td>{{ message.timestamp|date:'M d, Y H:i' }}</td>
                            <td>{{ message.sender|getUserNickname }}({{ message.sender }})</td>
                            {% if message.text|length > 40 %}
                            <td>{{ message.text|slice:'0 : 40' }} . . .</td>
                            {% else %}
                            <td>{{ message.text}}</td>
                            {% endif %}
                            <td>
                                <a href="{% url 'users:read_message' message.id %}" title="查看并回复">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'users:del_message' message.id %}" title="删除信息" onclick="delInboxMsgConfirm()">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                        {% endifequal %} {% empty %}
                        <tr>
                            <td>No message.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </form>
        </div>

        <br/>

        <a href="{% url 'users:call_admin' %}" class="btn btn-default">联系管理员</a>
        <a href="#" class="btn btn-default" style="background-color: white">回到顶部</a>
    </div>
</body>
{% endblock content %}

users/templates/users/mail_outbox.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load staticfiles %} {% load bootstrap4 %} {% load base %} {% block content %}

<script>
    //选中发件箱中的所有邮件
    function select_all_sendmsg() {
        var select_box = document.getElementById("send_select_all")
        var boxs = document.getElementsByName("checkbox_list");
        var flag = select_box.checked
        for (var i = 0; i < boxs.length; i++) {
            boxs[i].checked = flag;
        }
    }

    //警告框
    function delOutboxMsgConfirm() {
        event.returnValue = confirm("是否从'发件箱中'删除已经选择的信息？")
    }
</script>

<body>
    <div class="section-top-border-new">
        <h1><i class="fa fa-envelope-open-o"></i> 发件箱</h1>
        <br/>
        <div style="float:right">
            <a href="{% url 'users:mail_inbox' %}" class="btn btn-success">收件箱</a>
            <a href="{% url 'users:mail_outbox' %}" class="btn btn-info">发件箱</a>
        </div>
        <br/>

        <div class="section" id="outbox">
            <form action="{% url 'users:deal_mult_msg' %}" enctype="multipart/form-data" method="POST" class="form">{% csrf_token %}
                <button type="submit" class="btn btn-info" name="delete_msg" onclick="delOutboxMsgConfirm()">删除</button><br/><br/>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="send_select_all" onclick="select_all_sendmsg()"></th>
                            <th>时间</th>
                            <th>收信人</th>
                            <th>信件内容</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in outbox_messages %}
                        <tr>
                            <td><input type="checkbox" name="checkbox_list" value='{{message.id}}'></td>
                            <td>{{ message.timestamp|date:'M d, Y H:i' }}</td>
                            <td>{{ message.receiver|getUserNickname }}({{ message.receiver }})</td>
                            {% if message.text|length > 40 %}
                            <td>{{ message.text|slice:'0 : 40' }} . . .</td>
                            {% else %}
                            <td>{{ message.text}}</td>
                            {% endif %}
                            <td>
                                <a href="{% url 'users:read_message' message.id %}" title="查看信件">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'users:del_message' message.id %}" title="删除" onclick="delOutboxMsgConfirm()">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td>No message.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </form>
            <br/>
        </div>
        <a href="{% url 'users:call_admin' %}" class="btn btn-default">联系管理员</a>
        <a href="#" class="btn btn-default" style="background-color: white">回到顶部</a>
    </div>
</body>
{% endblock content %}

users/templates/users/read_message.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load staticfiles %} {% load bootstrap4 %}{% block content %} {% load base %}

<style>
    .message_display {
        border: 1px #ccc solid;
        border-radius: 6px;
        padding: 20px;
        margin-top: 10px;
    }
</style>

<body>
    <div class="section-top-border">
        <h2>查看信件</h2>
        <br/>
        <h4>发信人: {{ message.sender|getUserNickname }}({{ message.sender }})</h4>
        <br/>
        <p>{{ message.timestamp }}</p>
        <label>信息内容：</label>
        <div class="message_display">{{ message.text|safe }}</div>
        {% ifnotequal message.sender request.user %}
        <hr/>
        <h4>回复给发信人 {{ message.sender|getUserNickname }}:</h4>
        <br/>
        <form action="{% url 'users:send_message' message.sender.id %}" method="POST" class="form">{% csrf_token %}
            <div class="form-group">
                <label for="text">信息内容：</label>
                <textarea class="form-control" rows="8" name="text"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">回复</button>
            <a href="{% url 'users:mail_inbox' %}" class="btn btn-default">返回</a>
        </form>
        {% endifnotequal %}
    </div>

</body>
{% endblock content %}

users/templates/users/send_message.html
<!DOCTYPE html> {% extends "home/base.html" %} {% block content %} {% load static %} {% load bootstrap4 %} {% load base %}


<body>
    <div class="section-top-border">
        <h2>联系管理员:</h2>
        <hr/>
        <div class="col-md-10" style="float:left">
            <form action="{% url 'users:call_admin' %}" method="POST" class="form">{% csrf_token %}
                <div class="form-group">
                    <label for="text">信息内容：</label>
                    <textarea class="form-control" rows="8" name="text"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">发送</button>
                <a class="btn btn-outline-primary" href="javascript:history.go(-1)">返回上一步</a>
            </form>
        </div>
    </div>
</body>

{% endblock content %}

users/templates/users/settings.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load widget_tweaks %} {% block content %} {% load static %}

<link rel="stylesheet" href="{% static 'css/settings.css' %}">

<body>
    <div class="section-top-border">
        <h2> <i class="fa fa-user" style="margin-left:18px;"></i> 个人信息</h2>
        <div class="col-md-9" style="float:left">
            <form action="{% url 'users:settings' %}" enctype="multipart/form-data" method='post' novalidate class="myforms">
                {% csrf_token %}
                <hr/> {% for field in info_form %}
                <div class="form-group">
                    <span>
                    {{ field.label }}
                </span> {{ field | add_class:"form-control"}}
                    <p class="error-message text-danger">
                        {% for error in field.errors %} {{ error }} {% endfor %}
                    </p>
                </div>
                {% endfor %} {{ info_form.media }}

                <div class="form-group">
                    <span>头像(仅支持英文文件名)</span>
                    <input type="file" name="profile" class="form-control" />
                </div>

                <div style="text-align: center">
                    <button name="submit" class="btn btn-primary">提交</button>
                    <a class="btn btn-outline-primary" href="/">返回</a>
                </div>
            </form>
        </div>

        <div class="col-md-3" style="float:left; padding:0 0 0 60px;">
            <div style="margin:0 90px 0 0px;">
                <img class="img-circle" style="width:150px; height:150px; overflow:hidden;" src="/media/{{info.profile}}" alt="">
            </div>
        </div>
        <div class="col-md-3" style="float:left; padding:0px; margin-top: 50px">
            <div class="settings-border">
                <div class="settings-title" style="padding: 10px; margin: 0px">
                    <span class="glyphicon glyphicon-cog"></span> 功能
                    <hr/ style="margin: 5px">
                </div>
                <div class="function-item">
                    <a href="{% url 'users:reset_pwd' %}">修改密码</a>
                </div>
                <!-- <div class="function-item">
                    <a href="{% url 'users:call_admin' %}">查看公告</a>
                </div> -->
                <div class="function-item">
                    <a href="{% url 'users:call_admin' %}">联系管理员</a>
                </div>
                {% if info.is_verified == False %}
                <div class="function-item">
                    <a href="{% url 'users:stu_verify' %}" class="btn btn-success">用户学生认证</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

</body>
{% endblock content %}

users/templates/users/student_verify.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load widget_tweaks %} {% block content %} {% load static %}

<script type="text/javascript">
    function checknull() {　　
        var stu_card_photo = document.getElementById('stu_card_photo');
        if (stu_card_photo.value == "") {
            alert("提交的文件不能为空");
            return false;
        }
        return true;
    }
</script>

<body>
    <div class="section-top-border">
        <div style="margin-left: 100px">
            <h2>学生身份认证</h2>
            <br/>
            <p>Q：为什么我们需要学生身份认证？</p>
            <p>A：本闲置物品交易平台主要面向的对象是在校大学生，我们要确认用户的学生身份。</p>
            <p>Q：没有进行学生身份认证的影响？</p>
            <p>A：因无法确认学生身份，你将无法进入商品，聊天等系统。</p>
            <p>Q：如何进行学生身份认证？</p>
            <p>A：请在此处提交清晰的校园卡正面照片，后台审核通过后将会以站内邮件的形式通知你。</p>
            <p>O：更多疑问请 <a href="{% url 'users:call_admin' %}">【联系管理员】</a> </p>
            <br/>
            <div class="col-md-9" style="float:left">
                <form action="{% url 'users:stu_verify' %}" enctype="multipart/form-data" method='post' onsubmit="return checknull()">
                    {% csrf_token %}
                    <div class="form-group">
                        <span>校园卡/学生证信息照片（仅支持英文文件名）</span>
                        <input type="file" name="stu_card_photo" id="stu_card_photo" class="form-control" />
                    </div>

                    <div style="text-align: center">
                        <button name="submit" class="btn btn-primary">Submit</button>
                        <a class="btn btn-outline-primary" href="{% url 'users:settings' %}">Go Back</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
{% endblock content %}