AntMark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')), 
    path('users/', include('users.urls', namespace = 'users')),
    path('admin_manage/', include('admin_manage.urls', namespace = "admin_manage")),
    path('commodity/', include('commodity.urls', namespace = "commodity")),
    path('chatroom/',include('chatroom.urls', namespace = "chatroom")),
    path('ueditor/',include('DjangoUeditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\

admin_manage/urls.py
from django.urls import path

from admin_manage import views

app_name = 'admin_manage'

urlpatterns = [
    path('', views.admin_index, name = 'admin_index'),
    
    path('stu_verify_list', views.stu_verify_list, name = "stu_verify_list"),
    
    path('comm_verify_list', views.comm_verify_list, name = "comm_verify_list"),
    
    path('stu_verify_detail/<int:message_id>/<int:user_id>', views.stu_verify_detail, name = "stu_verify_detail"),

    path('comm_verify_detail/<int:message_id>/<int:comm_id>', views.comm_verify_detail, name = "comm_verify_detail"),

    path('create_anno/', views.create_anno, name = "create_anno"),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('del_message/<int:message_id>', views.del_message, name = 'del_message'),

    path('deal_mult_msg/', views.deal_mult_msg, name = 'deal_mult_msg'),
]

home/urls.py
from django.urls import path
import django.views

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name = 'index'),
    
    path('annos/', views.annos, name = 'annos'),

    path('about/', views.about, name = 'about'),
]

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    # 基础功能
    path('login/', views.login_view, name = 'login'),

    path('logout/', views.logout_view, name = 'logout'),

    path('register/', views.user_reg, name = 'register'),

    path('active/<str:active_code>', views.user_active, name = 'active'),

    path('settings/', views.user_settings, name = 'settings'),

    path('reset_pwd/', views.reset_password, name = 'reset_pwd'),

    path('personal_index/<int:user_id>', views.personal_index, name = 'personal_index'),

    path('stu_verify/', views.stu_verify, name = 'stu_verify'),

    
    # 消息处理相关
    path('mail_inbox/', views.mail_inbox, name = 'mail_inbox'),

    path('mail_outbox/', views.mail_outbox, name = 'mail_outbox'),

    path('call_admin/', views.call_admin, name = 'call_admin'),

    path('send_message/<int:user_id>', views.send_message, name = 'send_message'),

    path('set_as_read/<int:message_id>', views.set_as_read, name = 'set_as_read'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('del_message/<int:message_id>', views.del_message, name = 'del_message'),

    path('deal_mult_msg/', views.deal_mult_msg, name = 'deal_mult_msg'),

]

admin_manage/models.py
from django.db import models

# Create your models here.
class Announcement(models.Model):
    title = models.CharField(max_length=200, blank = False, default = None)
    text = models.CharField(max_length=20000)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('-timestamp', )
    def __str__(self):
        return self.text

admin_manage/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect, Http404, HttpResponse

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from helper.decorator import superuser_required

from commodity.models import Commodity
from users.models import UserInfo, Message
from admin_manage.models import Announcement

@login_required
@superuser_required
def admin_index(request):
    return render(request, 'admin_manage/index.html')

@login_required
@superuser_required
def stu_verify_list(request):
    # 这里默认只能是管理员才能登陆, request.user即为管理员
    inbox_messages = Message.objects.filter(receiver=request.user, 
        msg_type='stu_verify', receiver_del=False).order_by('-timestamp')
    outbox_messages = Message.objects.filter(sender=request.user, 
        msg_type='stu_verify', sender_del=False).order_by('-timestamp')
    context = {
        'function': "学生认证",
        'inbox_messages': inbox_messages,
        'outbox_messages': outbox_messages
    }
    return render(request, 'admin_manage/sp_mailbox.html', context)

@login_required
@superuser_required
def comm_verify_list(request):
    inbox_messages = Message.objects.filter(receiver=request.user, 
        msg_type='commodity_verify', receiver_del=False).order_by('-timestamp')
    outbox_messages = Message.objects.filter(sender=request.user, 
        msg_type='commodity_verify', sender_del=False).order_by('-timestamp')
    context = {
        'function': "商品",
        'inbox_messages': inbox_messages,
        'outbox_messages': outbox_messages
    }
    return render(request, 'admin_manage/sp_mailbox.html', context)


@login_required
@superuser_required
def stu_verify_detail(request, message_id, user_id):
    try:
        message = Message.objects.get(id=message_id)
        message.is_read = True
        message.save()
        stu_user = User.objects.get(id=user_id)
        stu_info = UserInfo.objects.get(user=stu_user)
    except ObjectDoesNotExist:
        raise Http404
    
    if stu_info.is_verified == True:
        response_data = {
            'message': "该用户已经完成学生验证",
            'next_page': "学生认证管理页面",
            'goto_url': settings.CUR_HOST + 'admin_manage/stu_verify_list',
            'goto_time': 3,
        }
        return render(request, 'users/notice.html' , response_data)

    if request.method == 'POST':
        text = request.POST['text']
        if 'verified' in request.POST:
            stu_info.is_verified = True
            stu_info.save()
        text = '【学生认证审核】 ' + text
        Message.objects.create(sender=request.user, receiver=stu_user, text=text)
        return HttpResponseRedirect(reverse('admin_manage:stu_verify_list'))

    context = { 
        'message': message,
        'stu_user': stu_user,
        'stu_info': stu_info,
    }
    return render(request, 'admin_manage/stu_verify_detail.html', context)    


@login_required
@superuser_required
def comm_verify_detail(request, message_id, comm_id):
    try:
        message = Message.objects.get(id=message_id)
        message.is_read = True
        message.save()
        comm = Commodity.objects.get(id=comm_id)
    except ObjectDoesNotExist:
        raise Http404

    if comm.is_verified == True:
        response_data = {
            'message': "商品已经完成审核，无须再次审核",
            'next_page': "商品审核管理页面",
            'goto_url': settings.CUR_HOST + 'admin_manage/comm_verify_list',
            'goto_time': 3,
        }
        return render(request, 'users/notice.html' , response_data)

    if request.method == 'POST':
        text = request.POST['text']
        if 'verified' in request.POST:
            comm.is_verified = True
            comm.save()
        text = '【商品审核】 你的商品 [' + comm.title + '] 的审核结果 ' + text
        Message.objects.create(sender=request.user, receiver=comm.owner, text=text)
        return HttpResponseRedirect(reverse('admin_manage:comm_verify_list'))

    context = {
        'message': message, 
        'comm': comm,
        }
    return render(request, 'admin_manage/comm_verify_detail.html', context)


@login_required
@superuser_required
def create_anno(request):
    """ 管理员发布公告 """
    if request.method == 'POST':
        response_data = {
            'message': "公告内容不可为空",    
            'next_page': "管理员后台主页",
            'goto_url': settings.CUR_HOST + 'admin_manage',
            'goto_time': 2,
        }
        title = request.POST['title']
        text = request.POST['text']
        if text:
            Announcement.objects.create(text=text, title = title)
            response_data['message'] = "你已创建新的公告"        
        return render(request, 'users/notice.html' , response_data)

    return render(request, 'admin_manage/create_anno.html')


@login_required
@superuser_required
def read_message(request, message_id):
    """ 阅读消息完整内容 """
    message = Message.objects.get(id=message_id)
    if request.user == message.receiver:
        message.is_read = True
        message.save()

    context = { 'message': message }
    return render(request, 'admin_manage/sp_read_message.html', context)


@login_required
@superuser_required
def del_message(request, message_id):
    """ 某方删除当前消息，若另一方已删除，则删除该信息 """
    try:
        del_message = Message.objects.get(id=message_id)
    except ObjectDoesNotExist:
        raise Http404
    if del_message.msg_type == 'stu_verify':           
        del_message.delete()
        return HttpResponseRedirect(reverse('admin_manage:stu_verify_list'))
    elif del_message.msg_type == 'commodity_verify':
        del_message.delete()
        return HttpResponseRedirect(reverse('admin_manage:comm_verify_list'))


@login_required
@superuser_required
def deal_mult_msg(request):
    msg_ids = request.POST.getlist("checkbox_list")
    if 'delete_msg' in request.POST:
        for idx in msg_ids:
            response = del_message(request, int(idx))
    if 'response' in locals().keys():
        return response
    return HttpResponseRedirect(reverse('users:mail_inbox'))

admin_manage/templates/admin_manage/comm_verify_detail.html
<!DOCTYPE html> {% extends "home/base.html" %} {% block title %} Index {% endblock %} {% load static %} {% block content %}

<html lang="zxx">

<script>
    //向消息发送框中填入审核成功的消息
    function addSuccessMsg() {
        document.getElementById('failmsg').style.display = 'none'
        document.getElementById('verified').checked = true
        document.getElementById('unverified').checked = false;
        document.getElementById('text').value = "信息合法，商品审核通过。"
    }

    //提供默认的失败消息模板以供选择
    function displayFailMsgBlock() {
        document.getElementById('verified').checked = false;
        document.getElementById('unverified').checked = true;
        document.getElementById('text').value = "商品审核未通过，原因如下："
        var unverified = document.getElementById('unverified')
        var failmsgblock = document.getElementById('failmsg')
        if (unverified.checked == false)
            failmsgblock.style.display = 'none'
        else
            failmsgblock.style.display = 'block'
    }

    function addFailMsg(msg) {
        document.getElementById('text').value += msg;
    }
</script>

<body>
    <section class="section-top-border project-area section-gap" style="padding-top: 20px">
        <div class="container">
            <div class="title text-center">
                <h2 class="mb-10">商品审核</h2>
            </div>
            <br/>
            <div>
                <div class="col-md-10">
                    <div class="row">
                        <div class="col-md-5" style="padding: 5px; width: 390px; height: 390px; margin-right: 10px;">
                            {% if comm.image %}
                            <img src="{{comm.image | striptags}}" height="380px" class="center-block"> {% else %}
                            <img src="{% static 'img/defaultImage.jpg' %}" height="380px" class="center-block"> {% endif %}
                        </div>
                        <div class="col-md-7">
                            <h3>{{comm.title}}</h3>
                            <br>
                            <div class="row" style="margin-top: 10px;">
                                <div class="col-md-2 text-left">价格：</div>
                                <div class="col-md-10 text-left">￥{{comm.price}}</div>
                            </div>
                            <div class="row" style="margin-top: 10px;">
                                <div class="col-md-2 text-left">卖家：</div>
                                <div class="col-md-10 text-left">
                                    <a href="{% url 'users:personal_index' comm.owner.id %}"></a>{{comm.owner}}</a>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 10px;">
                                <div class="col-md-2 text-left">货源：</div>
                                <div class="col-md-10 text-left">{{comm.commodity_source}}</div>
                            </div>
                        </div>
                    </div>
                    <br>
                    <hr>
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-12">
                            <h4>商品详情</h4>
                            <div style="border:1px solid rgb(230, 230, 230); padding: 10px; overflow-x: hidden;">
                                {% autoescape off %} {{comm.body}} {% endautoescape %}
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
            <hr/>
            <div>
                <form action="{% url 'admin_manage:comm_verify_detail' message.id comm.id %}" method="POST" class="form">{% csrf_token %}
                    <input type="checkbox" name="verified" id='verified' onclick="addSuccessMsg()" checked=true>审核通过
                    <input type="checkbox" name="unverified" id='unverified' onclick="displayFailMsgBlock()">审核不通过
                    <div id="failmsg" style="display: none;">
                        <p>快捷回复：</p>
                        <p>
                            <input type="checkbox" onclick="addFailMsg('#商品信息不完善，检查封面时候缺失，描述是否有误 ')">
                            <span>商品信息不完善，检查封面时候缺失，描述是否有误</span>
                        </p>
                        <p>
                            <input type="checkbox" onclick="addFailMsg('#商品内容涉及黄暴恐，严肃整改 ')">
                            <span>商品内容涉及黄暴恐，严肃整改</span>
                        </p>
                    </div>
                    <div class="form-group">
                        <label for="text">信息内容：</label>
                        <textarea class="form-control" rows="5" name="text" id="text" style="width:
                            95%">信息合法，商品审核通过。</textarea>
                    </div>
                    <div style="float: right;margin-right:5%">
                        <button type="submit" class="btn btn-primary ">提交审核结果</button>
                        <a class="btn btn-default " href="javascript:history.go(-1) ">返回</a>
                    </div>
                </form>
            </div>
        </div>
    </section>
</body>

</html>

{% endblock content %}

admin_manage/templates/admin_manage/create_anno.html
<!DOCTYPE html> {% extends "home/base.html" %} {% block content %} {% load static %} {% load bootstrap4 %} {% load base %}


<body>
    <div class="section-top-border">
        <ol class="breadcrumb" style="background-color:rgba(128, 128, 128, 0.055);margin-left: -10px">
            <li class="breadcrumb-item"><a href="{% url 'admin_manage:admin_index' %}">管理员后台</a></li>
            <li class="breadcrumb-item active">发布公告</li>
        </ol>
        <div class="col-md-10" style="float:left">
            <h2>发布公告</h2>
            <hr/>
        </div>
        <div class="col-md-10" style="float:left">
            <form action="{% url 'admin_manage:create_anno' %}" method="POST" class="form">{% csrf_token %}
                <div class="form-group">
                    <label for="title">公告标题：</label>
                    <input class="form-control" rows="8" name="title">
                </div>                
                <div class="form-group">
                    <label for="text">公告内容：</label>
                    <textarea class="form-control" rows="8" name="text"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">发送</button>
                <a class="btn btn-outline-primary" href="javascript:history.go(-1)">返回上一步</a>
            </form>
        </div>
    </div>
</body>

{% endblock content %}

admin_manage/templates/admin_manage/index.html
<!DOCTYPE html> {% extends "home/base.html" %} {% block title %} Index {% endblock %} {% load static %} {% block content %}

<html lang="zxx" class="no-js">

<body>
    <!-- <section class="project-area section-gap" style="padding-top: 50px"> -->
    <section class="section-gap" style="padding-top: 50px">
        <div class="container">
            <div class="title text-center">
                <h1 class="mb-10">AntMark 管理员后台审核中心 </h1>
                <br>
                <p class="mb-10">欢迎回来</p>
                <br /><br />
                <a href="{% url 'admin_manage:stu_verify_list' %}" class="btn btn-primary" style="margin-left:-30px">学生认证审核</a>
                <a href="{% url 'admin_manage:comm_verify_list' %}" class="btn btn-primary" style="margin-left:40px">商品审核</a>
                <a href="{% url 'admin_manage:create_anno' %}" class="btn btn-primary" style="margin-left:40px">发布公告</a>
            </div>
        </div>
    </section>
</body>

</html>

{% endblock content %}

admin_manage/templates/admin_manage/sp_mailbox.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load staticfiles %} {% load bootstrap4 %} {% load base %}
{% block content %}

<script>
    //选中收件箱中的所有邮件
    function select_all_recemsg() {
        var select_box = document.getElementById("rece_select_all")
        var boxs = document.getElementsByName("checkbox_list");
        var flag = select_box.checked
        for (var i = 0; i < boxs.length; i++) {
            boxs[i].checked = flag;
        }
    }

    //警告框
    function delMsgConfirm() {
        event.returnValue = confirm("是否从 收件箱中 删除已经选择的信息？")
    }
</script>

<body>
    <div class="section-top-border-new">
        <!-- <ol class="breadcrumb" style="background-color:rgba(128, 128, 128, 0.055);margin-left: -10px">
            <li class="breadcrumb-item"><a href="{% url 'admin_manage:admin_index' %}">管理员后台</a></li>
            <li class="breadcrumb-item active">{{function}}审核系统</li>
        </ol> -->
        <h1>{{ function }}审核系统</h1>

        <!-- <div style="float:right">
            <a href="{% url 'admin_manage:stu_verify_list' %}" class="btn btn-success">学生认证审核系统</a>
            <a href="{% url 'admin_manage:comm_verify_list' %}" class="btn btn-info">商品审核系统</a>
        </div> -->
        <br />

        <div class="section" id="inbox">
            <form action="{% url 'admin_manage:deal_mult_msg' %}" enctype="multipart/form-data" method="POST"
                class="form">{% csrf_token %}

                <div>
                    <div style="float:left">
                        <button type="submit" class="btn btn-info" name="delete_msg"
                            onclick="delMsgConfirm()">删除</button>
                    </div>
                    <div style="float:right">
                        <a href="{% url 'admin_manage:stu_verify_list' %}" class="btn btn-success">学生认证审核系统</a>
                        <a href="{% url 'admin_manage:comm_verify_list' %}" class="btn btn-info">商品审核系统</a>
                    </div>
                    <br><br>
                </div>

                
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="rece_select_all" onclick="select_all_recemsg()"></th>
                            <th>时间</th>
                            <th>发信人</th>
                            <th>信件内容</th>
                            <th>查看</th>
                            <th>审核</th>
                            <th>删除</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in inbox_messages %} {% ifequal message.is_read False %}
                        <tr class="info">
                            <td><input type="checkbox" name="checkbox_list" value='{{message.id}}'></td>
                            <td>{{ message.timestamp|date:'M d, Y H:i' }}</td>
                            <td>{{ message.sender|getUserNickname }}({{ message.sender }})</td>
                            {% if message.text|length > 40 %}
                            <td>{{ message.text|slice:'0 : 40' }} . . .</td>
                            {% else %}
                            <td>{{ message.text}}</td>
                            {% endif %}
                            <td>
                                <a href="{% url 'admin_manage:read_message' message.id %}" title="查看">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                </a>
                            </td>
                            <td>
                                {% ifequal message.msg_type 'stu_verify' %}
                                <a href="{% url 'admin_manage:stu_verify_detail' message.id message.id_content %}"
                                    title="审核">
                                    <span class="glyphicon glyphicon-search " aria-hidden="true "></span>
                                </a>
                                {% else %}
                                <a href="{% url 'admin_manage:comm_verify_detail' message.id message.id_content %}"
                                    title="审核">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </a>
                                {% endifequal %}
                            </td>
                        </tr>
                        {% else %}
                        <tr>
                            <td><input type="checkbox" name="checkbox_list" value='{{message.id}}'></td>
                            <td>{{ message.timestamp|date:'M d, Y H:i' }}</td>
                            <td>{{ message.sender|getUserNickname }}({{ message.sender }})</td>
                            {% if message.text|length > 40 %}
                            <td>{{ message.text|slice:'0 : 40' }} . . .</td>
                            {% else %}
                            <td>{{ message.text}}</td>
                            {% endif %}
                            <td>
                                <a href="{% url 'admin_manage:read_message' message.id %}" title="查看">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                </a>
                            </td>
                            <td>
                                {% ifequal message.msg_type 'stu_verify' %}
                                <a href="{% url 'admin_manage:stu_verify_detail' message.id message.id_content %}"
                                    title="审核">
                                    <span class="glyphicon glyphicon-search " aria-hidden="true "></span>
                                </a>
                                {% else %}
                                <a href="{% url 'admin_manage:comm_verify_detail' message.id message.id_content %}"
                                    title="审核">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </a>
                                {% endifequal %}
                            </td>
                            <td>
                                <a href="{% url 'admin_manage:del_message' message.id %}" title="删除信息"
                                    onclick="delMsgConfirm()">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                        {% endifequal %} {% empty %}
                        <tr>
                            <td>No message.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </form>
            <br />
        </div>

        <a href="#" class="btn btn-default" style="background-color: white">回到顶部</a>
        <!-- <a href="{% url 'home:index' %}" class="btn btn-default">返回主页</a> -->
    </div>
</body>
{% endblock content %}

admin_manage/templates/admin_manage/sp_read_message.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load staticfiles %} {% load bootstrap4 %}{% block content %}
{% load base %}



<body>
    <div class="section-top-border">
        <!-- <ol class="breadcrumb" style="background-color:rgba(128, 128, 128, 0.055);margin-left: -10px">
            <li class="breadcrumb-item"><a href="{% url 'admin_manage:admin_index' %}">管理员后台</a></li>
            {% if message.msg_type == 'stu_verify' %}
            <li class="breadcrumb-item"><a href="{% url 'admin_manage:stu_verify_list' %}">学生认证审核系统</a></li>
            {% else %}
            <li class="breadcrumb-item"><a href="{% url 'admin_manage:comm_verify_list' %}">商品审核系统</a></li>
            {% endif %}
            <li class="breadcrumb-item">查看信件</li>
        </ol> -->
        <h2>查看信件</h2>
        <br />
        <h4>发信人: {{ message.sender|getUserNickname }}({{ message.sender }})</h4>
        <br />
        <p>{{ message.timestamp }}</p>
        <label>信息内容：</label>
        <div class="message_display">{{ message.text|safe }}</div>
        {% ifnotequal message.sender request.user %}
        <hr />
        <h4>回复给发信人 {{ message.sender|getUserNickname }}:</h4>
        <br />
        <form action="{% url 'users:call_admin' %}" method="POST" class="form">{% csrf_token %}
            <div class="form-group">
                <label for="text">信息内容：</label>
                <textarea class="form-control" rows="8" name="text"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">回复</button>
        </form>
        {% endifnotequal %}

        
        <div>
            <br />
            {% if message.msg_type == 'stu_verify' %}
            <a href="{% url 'admin_manage:stu_verify_list' %}" class="btn btn-default">返回</a>
            {% else %}
            <a href="{% url 'admin_manage:comm_verify_list' %}" class="btn btn-default">返回</a>
            {% endif %}
        </div>
    </div>

</body>
{% endblock content %}

admin_manage/templates/admin_manage/stu_verify_detail.html
<!DOCTYPE html> {% extends "home/base.html" %} {% block title %} Index {% endblock %} {% load static %} {% block content %}

<html lang="zxx">

<script>
    //向消息发送框中填入审核成功的消息
    function addSuccessMsg() {
        document.getElementById('failmsg').style.display = 'none'
        document.getElementById('verified').checked = true;
        document.getElementById('unverified').checked = false;
        document.getElementById('text').value = "信息合法，学生身份审核通过。"
    }

    //提供默认的失败消息模板以供选择
    function displayFailMsgBlock() {
        document.getElementById('verified').checked = false;
        document.getElementById('unverified').checked = true;
        document.getElementById('text').value = "学生身份审核未通过，原因如下："
        var unverified = document.getElementById('unverified')
        var failmsgblock = document.getElementById('failmsg')
        if (unverified.checked == false)
            failmsgblock.style.display = 'none'
        else
            failmsgblock.style.display = 'block'
    }

    function addFailMsg(msg) {
        document.getElementById('text').value += msg;
    }
</script>

<body>
    <section class="section-top-border project-area section-gap" style="padding-top: 20px">
        <div class="container">
            <div class="title text-center">
                <h2 class="mb-10">学生身份认证审核</h2>
            </div>
            <br/>

            <div>
                <div class="profile_border" style="float: left">
                    <p>用户头像:</p>
                    <img style="height: 300px" src="/media/{{stu_info.profile}}">
                </div>
                <div style="float: left; padding-left:10%">
                    <p>用户个人信息：</p>
                    <br/>
                    <p>Username: {{ stu_user.username }}</p>
                    <p>Nickname: {{ stu_info.nickname }}</p>
                    <p>Gender: {{ stu_info.gender }}</p>
                    <p>Introduce: {{ stu_info.intro }}</p>
                    <p>Phone: {{ stu_info.phone }}</p>
                    <p>Wechat: {{ stu_info.wechat }}</p>
                    <p>QQ: {{ stu_info.qq }}</p>
                </div>
                <div class="profile_border" style="float:left; padding-left:10%">
                    <p>用户校园卡照片</p>
                    <img style="height: 300px" src="/media/{{stu_info.stuCardPhoto}}">
                </div>
                <div class="clear"></div>
                <hr/>
                <form action="{% url 'admin_manage:stu_verify_detail' message.id stu_user.id %}" method="POST" class="form">{% csrf_token %}
                    <input type="checkbox" name="verified" id='verified' onclick="addSuccessMsg()" checked=true>审核通过
                    <input type="checkbox" name="unverified" id='unverified' onclick="displayFailMsgBlock()">审核不通过
                    <div id="failmsg" style="display: none">
                        <p>快捷回复：</p>
                        <p>
                            <input type="checkbox" onclick="addFailMsg('#校园卡/学生证照片不清晰 ')">
                            <span>校园卡/学生证照片不清晰</span>
                        </p>
                        <p>
                            <input type="checkbox" onclick="addFailMsg('#请上传能够证明学生身份的照片 ')">
                            <span>请上传能够证明学生身份的照片</span>
                        </p>
                    </div>
                    <div class="form-group">
                        <label for="text">信息内容：</label>
                        <textarea class="form-control" rows="5" name="text" id="text" style="width:95%">信息合法，学生身份审核通过。</textarea>
                    </div>
                    <div style="float: right;margin-right:5%">
                        <button type="submit" class="btn btn-primary ">提交审核结果</button>
                        <a class="btn btn-default " href="javascript:history.go(-1) ">返回</a>
                    </div>
                </form>
            </div>
        </div>
    </section>
</body>

</html>

{% endblock content %}